.PHONY: all invoke import usage export callback slices main
all: invoke export callback slices main

invoke:
	./build.sh invoke

import:
	./build.sh import

usage:
	./build.sh usage

export:
	./build.sh export

callback:
	./build.sh callback

slices:
	./build.sh slices

main:
	./build.sh main

clean:
	rm -rf compiled/*